name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Replace with your desired PHP version

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Build assets (optional)
        run: npm install && npm run production

      - name: Deploy to production (replace with your deployment steps)
        run: |
          ssh sylvester@198.58.101.124 'cd /var/www/journal && git pull origin main && composer install --no-progress --no-interaction --prefer-dist && php artisan migrate --force'
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
