name: Journal Africa CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Replace with your desired PHP version

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Build assets (optional)
        run: npm install

      - name: Deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no sylvester@198.58.101.124 'cd /var/www/html/sshjournal && git pull origin main && composer install --no-progress --no-interaction --prefer-dist && php artisan migrate --force'
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
